
# ═══════════════════════════════════════════════════════════════
# 🚀 Generated by GitMaxer (Free Plan)
# 🔗 Upgrade at https://gitmaxer.vercel.app for watermark-free code
# ═══════════════════════════════════════════════════════════════

# Learning Objective:
# This tutorial will teach you how to generate unique, random visual art patterns
# using Python's Turtle graphics library and basic algorithmic thinking.
# We will focus on creating patterns by combining random movements, colors, and shapes.

import turtle
import random

# --- Setup ---
# Initialize the turtle screen. This is our canvas.
screen = turtle.Screen()
screen.setup(width=800, height=600)  # Set the window dimensions
screen.bgcolor("black")             # Set the background color to black for contrast

# Create a turtle object. This is our "pen" that will draw on the screen.
painter = turtle.Turtle()
painter.speed(0)  # Set the drawing speed to the fastest (0). We want the art, not the drawing process.
painter.hideturtle() # Hide the turtle icon itself so it doesn't interfere with the art.
painter.pensize(2) # Make the lines slightly thicker for better visibility.

# --- Core Concept: Randomly Driven Drawing ---
# The core idea here is to make decisions randomly at each step of the drawing
# process. This ensures that each time we run the code, we get a different,
# unique pattern.

def draw_random_pattern(num_shapes=50):
    """
    Draws a random visual art pattern by repeatedly drawing simple shapes
    with random positions, colors, and orientations.

    Args:
        num_shapes (int): The number of individual shapes to draw in the pattern.
    """
    for _ in range(num_shapes): # Loop 'num_shapes' times to draw each part of the pattern.
        # 1. Random Color Selection:
        # We need a way to pick random colors. RGB (Red, Green, Blue) values range from 0 to 1.
        # random.random() generates a float between 0.0 and 1.0.
        r = random.random()
        g = random.random()
        b = random.random()
        painter.pencolor(r, g, b) # Set the pen color for the next shape.

        # 2. Random Position:
        # We want shapes to appear all over the screen.
        # The screen width is 800, so valid x coordinates are roughly -400 to 400.
        # The screen height is 600, so valid y coordinates are roughly -300 to 300.
        x_pos = random.randint(-350, 350)
        y_pos = random.randint(-250, 250)

        # Move the turtle to the random position without drawing a line.
        painter.penup() # Lift the pen so it doesn't draw while moving.
        painter.goto(x_pos, y_pos) # Go to the chosen random coordinates.
        painter.pendown() # Put the pen down to start drawing again.

        # 3. Random Shape and Size:
        # We'll choose between drawing a circle or a square randomly.
        # random.choice() picks one item from a list.
        shape_type = random.choice(["circle", "square"])

        # The size of the shape will also be random.
        size = random.randint(10, 50) # Shapes will be between 10 and 50 units in size.

        if shape_type == "circle":
            # Draw a circle. The 'extent' is the angle of the arc (360 for a full circle).
            # The 'steps' parameter can make circles look smoother but we'll skip it for simplicity.
            painter.circle(size)
        else: # It must be a square
            # Draw a square. We'll turn 90 degrees after each side.
            for _ in range(4):
                painter.forward(size) # Draw one side of the square.
                painter.right(90)     # Turn right by 90 degrees.

        # 4. Random Orientation (for squares):
        # Even if we draw a square, we can rotate it before drawing.
        # This adds more visual variety.
        if shape_type == "square":
            rotation = random.randint(0, 360) # Random rotation angle.
            painter.right(rotation) # Rotate the turtle by the random amount.
            # Note: We move to a new random position *before* drawing,
            # so the rotation mainly affects how the square is oriented at its random location.

# --- Example Usage ---

# Clear the screen before drawing a new pattern. Useful if you want to draw multiple patterns.
# painter.clear()

# Draw a pattern with 100 shapes.
draw_random_pattern(num_shapes=100)

# Keep the window open until it's manually closed.
screen.mainloop()